# -*- coding: utf-8 -*-
"""Bollywood.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DwdoUK_cUtvOsjHmYQZgmV6xfwAXNm16
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('bollywood.csv')

list(df.columns)

plt.style.use('ggplot')
df.shape

df.head(5)

df.columns

df.info()

count= df.Genre.value_counts()
print(count)

sns.boxplot(x='Genre',y='YoutubeLikes',data=df);

df['Genre'].value_counts().idxmax()

df[['Genre','MovieName']].sort_values ('Genre',ascending=False)

pd.crosstab(df['Genre'],df['ReleaseTime'])

pd.crosstab(df['Genre'],df['ReleaseTime']).value_counts()

df.groupby(['Genre', 'ReleaseTime']).size()

filtered=df[(df['ReleaseTime']=='LW')&(df['ReleaseTime']=='FS') ]

genre_counts = filtered['Genre'].value_counts()
print(genre_counts)

df['Release Date'] = pd.to_datetime(df['Release Date'])
df['Month'] = df['Release Date'].dt.month_name()
df['Month'].value_counts().idxmax()

df['Month'].value_counts()

high_budget = df[df['Budget'] > 25]
high_budget['Month'].value_counts().idxmax()

df['roi']=(df['BoxOfficeCollection']-df['Budget'])/(df['Budget'])
df.roi

top10_roi = df[['MovieName', 'roi']].sort_values(by='roi', ascending=False).head(10)
top10_roi.reset_index(drop=True, inplace=True)
top10_roi

sns.barplot(x='MovieName',y='Budget',data=df);

plt.hist(df['Budget']);

sns.distplot(df['Budget'])

infuential_features=['Budget','BoxOfficeCollection','YoutubeViews','YoutubeLikes','YoutubeDislikes']
infuential_features
sns.pairplot(df[infuential_features],size=2)